threads: []
posts:
  - "https://www.doomworld.com/forum/post/3036699"
  - "https://www.doomworld.com/forum/post/3037026"
  - "https://www.doomworld.com/forum/post/3036925"
  - "https://www.doomworld.com/forum/post/3036782"
