posts:
  - "https://www.doomworld.com/forum/post/2110660"
  - "https://www.doomworld.com/forum/post/2378077"
  - "https://www.doomworld.com/forum/post/2378509"
  - "https://www.doomworld.com/forum/post/2381401"
  - "https://www.doomworld.com/forum/post/2384888"
  - "https://www.doomworld.com/forum/post/2466791"
  - "https://www.doomworld.com/forum/post/2469765"
  - "https://www.doomworld.com/forum/post/2471107"
  - "https://www.doomworld.com/forum/post/2471131"
  - "https://www.doomworld.com/forum/post/2476113"
  - "https://www.doomworld.com/forum/post/2477730"
  - "https://www.doomworld.com/forum/post/2478056"
  - "https://www.doomworld.com/forum/post/2485336"
  - "https://www.doomworld.com/forum/post/2498096"
  - "https://www.doomworld.com/forum/post/2499616"
  - "https://www.doomworld.com/forum/post/2500282"
  - "https://www.doomworld.com/forum/post/2510790"
