threads: []
posts:
  - "https://www.doomworld.com/forum/post/2758234"
  - "https://www.doomworld.com/forum/post/2825016"
  - "https://www.doomworld.com/forum/post/2825132"
  - "https://www.doomworld.com/forum/post/2825321"
  - "https://www.doomworld.com/forum/post/2828804"
  - "https://www.doomworld.com/forum/post/2835030"
