threads: []
posts:
  - "https://www.doomworld.com/forum/post/2816829"
  - "https://www.doomworld.com/forum/post/2820985"
  - "https://www.doomworld.com/forum/post/2821632"
  - "https://www.doomworld.com/forum/post/2821053"
  - "https://www.doomworld.com/forum/post/2811959"
  - "https://www.doomworld.com/forum/post/2813157"
