posts:
  - "https://www.doomworld.com/forum/post/2590450"
  - "https://www.doomworld.com/forum/post/2590459"
  - "https://www.doomworld.com/forum/post/2590465"
  - "https://www.doomworld.com/forum/post/2590475"
  - "https://www.doomworld.com/forum/post/2528619"
  - "https://www.doomworld.com/forum/post/2529774"
  - "https://www.doomworld.com/forum/post/2529796"
  - "https://www.doomworld.com/forum/post/2532391"
  - "https://www.doomworld.com/forum/post/2586801"
  - "https://www.doomworld.com/forum/post/2556894"
  - "https://www.doomworld.com/forum/post/2556989"
  - "https://www.doomworld.com/forum/post/2557377"
  - "https://www.doomworld.com/forum/post/2557843"
  - "https://www.doomworld.com/forum/post/2558781"
  - "https://www.doomworld.com/forum/post/2559583"
  - "https://www.doomworld.com/forum/post/2559923"
  - "https://www.doomworld.com/forum/post/2575130"
