posts:
  - "https://www.doomworld.com/forum/post/2466528"
  - "https://www.doomworld.com/forum/post/2467307"
  - "https://www.doomworld.com/forum/post/2467392"
  - "https://www.doomworld.com/forum/post/2468237"
  - "https://www.doomworld.com/forum/post/2469415"
  - "https://www.doomworld.com/forum/post/2477535"
  - "https://www.doomworld.com/forum/post/2477797"
  - "https://www.doomworld.com/forum/post/2477922"
