threads: []
posts:
  - "https://www.doomworld.com/forum/post/2560181"
  - "https://www.doomworld.com/forum/post/2563550"
  - "https://www.doomworld.com/forum/post/2563853"
  - "https://www.doomworld.com/forum/post/2565274"
