threads: []
posts:
  - "https://www.doomworld.com/forum/post/2303824"
  - "https://www.doomworld.com/forum/post/2303825"
  - "https://www.doomworld.com/forum/post/2458982"
  - "https://www.doomworld.com/forum/post/2460680"
  - "https://www.doomworld.com/forum/post/2460691"
  - "https://www.doomworld.com/forum/post/2463831"
  - "https://www.doomworld.com/forum/post/2486680"
  - "https://www.doomworld.com/forum/post/2490300"
  - "https://www.doomworld.com/forum/post/2503895"
  - "https://www.doomworld.com/forum/post/2504713"
